[package]
name = "gta-img"
authors = ["Connor Haigh"]
description = "gta-img is a library for manipulating 3D-universe Grand Theft Auto IMG/DIR files."
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.4", features = ["derive"] }
